# For variables in the Makefile use $(variable)
# For variables on the host use $${variable}
# For command substitution on the host use $$(command)
# For variables in the container use \$${variable}
# For command substitution in the container use \$$(command)
#
# Also, don't forget `make rule_here -n` aka --just-print
